name: r_nav_n_sheet
description: Animated, modern and highly customisable bottom navigation bar for flutter.
version: 1.1.0
homepage: https://github.com/rajyadavnp/r_nav_n_sheet
repository: https://github.com/rajyadavnp/r_nav_n_sheet

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nes_ui: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true